apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bnetserver.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "bnetserver.name" . }}
    helm.sh/chart: {{ include "bnetserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  database.json: |-
    {
      "development": {
        "username": "{{.Values.mysqlConfig.development.username}}",
        "password": "{{.Values.mysqlConfig.development.password}}",
        "database": "{{.Values.mysqlConfig.development.database}}",
        "host": "{{.Values.mysqlConfig.development.hostname}}",
        "dialect": "mysql",
        "dialectOptions": {
          "bigNumberStrings": true
        }
      },
      "test": {
        "username": "{{.Values.mysqlConfig.test.username}}",
        "password": "{{.Values.mysqlConfig.test.password}}",
        "database": "{{.Values.mysqlConfig.test.database}}",
        "host": "{{.Values.mysqlConfig.test.hostname}}",
        "dialect": "mysql",
        "dialectOptions": {
          "bigNumberStrings": true
        }
      },
      "production": {
        "username": "{{.Values.mysqlConfig.production.username}}",
        "password": "{{.Values.mysqlConfig.production.password}}",
        "database": "{{.Values.mysqlConfig.production.database}}",
        "host": "{{.Values.mysqlConfig.production.hostname}}",
        "dialect": "mysql",
        "dialectOptions": {
          "bigNumberStrings": true
        }
      }
    }
  winston.json: |-
    {
        "level": "info",
        "filename": "./logs/all-logs.log",
        "handleExceptions": true,
        "json": true,
        "maxsize": 5242880,
        "maxFiles": 5,
        "colorize": false
    }