apiVersion: v1
kind: Service
metadata:
  name: {{ include "bnetserver.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "bnetserver.name" . }}-frontend
    helm.sh/chart: {{ include "bnetserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 1119
      targetPort: 1119
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "bnetserver.name" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
