apiVersion: v1
kind: Service
metadata:
  name: {{ include "bnetserver.fullname" . }}-rest
  labels:
    app.kubernetes.io/name: {{ include "bnetserver.name" . }}-rest
    helm.sh/chart: {{ include "bnetserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "bnetserver.name" . }}-rest
    app.kubernetes.io/instance: {{ .Release.Name }}
