apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bnetserver.fullname" . }}-tls-secret
  labels:
    app.kubernetes.io/name: {{ include "bnetserver.name" . }}
    helm.sh/chart: {{ include "bnetserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{ (.Files.Glob "certs/*").AsSecrets | indent 2 }}